name: Release to Server

on:
  release:
    types: [published, created]

jobs:
  deploy-installer:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get release version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "installer_name=Game Cheats Manager Setup $VERSION.exe" >> $GITHUB_OUTPUT

      - name: Delete previous installer
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_GCM_PREFIX: "GCM"
        run: |
          aws s3 ls s3://${S3_BUCKET_NAME}/${S3_GCM_PREFIX}/ | grep "Game Cheats Manager Setup" || true
          aws s3 rm s3://${S3_BUCKET_NAME}/${S3_GCM_PREFIX}/ --recursive --exclude "*" --include "Game Cheats Manager Setup*.exe"
          echo "Previous installers deleted from s3://${S3_BUCKET_NAME}/${S3_GCM_PREFIX}/"

      - name: Upload new installer to AWS S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_GCM_PREFIX: "GCM"
        run: |
          aws s3 cp ./Game Cheats Manager Setup ${{ steps.get_version.outputs.version }}.exe s3://${S3_BUCKET_NAME}/${S3_GCM_PREFIX}/Game Cheats Manager Setup ${{ steps.get_version.outputs.version }}.exe
          echo "Game Cheats Manager Setup ${{ steps.get_version.outputs.version }}.exe uploaded to s3://${S3_BUCKET_NAME}/${S3_GCM_PREFIX}/Game Cheats Manager Setup ${{ steps.get_version.outputs.version }}.exe"
